### ISSUE TITLE
Multiple PosOrient windows

### ISSUE THREAD

**Issue by speters** [jacmie/PosOrient#2]
I noticed that it is possible to open multiple PosOrient dialogues at the same time:
![Screenshot_20241030-173920](https://github.com/user-attachments/assets/c007fa2b-e46a-4f6a-8ec2-45b009f78637)
Whileas not exactly an error, it might be undesired behaviour.

Kind regards from Hamburg, Germany,
Sönke

**Comment by jacmie** [comment]
Done ;)
Plugin's dialog doesn't reopen when it is running. 
The dialog remains interactive with KiCad, footprints can be moved and edited while the dialog is opened.
Changes present in the release v1.1.3
